on: [push] # Run workflow on every push
jobs:
  matlab-build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2-rc

      - name: Run tests
        uses: matlab-actions/run-tests@v2-rc
        with:
            source-folder: src
